### ISSUE TITLE
请问，ShowCore和小飞在线连接需要特殊配置吗？

### ISSUE THREAD

**Issue by jixiaoyong** [iFLYOS-OPEN/SDK-Android#1]
您好，我下载并运行了ShowCore 到我的设备上，连接WiFi后提示“扫码绑定设备”。
之后按照提示下载、注册了小飞在线并绑定了酷狗账号，但是在 主控设备 -> 添加主控设备 ->有屏DEMO 扫码结果提示:
```
无效应用
由于未知、不支持或没有客户端，认证失败
```
请问是我添加方式有误，还是需要修改ShowCore部分配置信息？在官网未找到对应信息，请求指导一下如何绑定，谢谢！

**Comment by xingrz** [comment]
将 [ShowCore/build.gradle#L64](https://github.com/iFLYOS-OPEN/SDK-Android/blob/v1.x-oss/ShowCore/build.gradle#L64) 里的 CLIENT_ID 改成 `"ceb62135-38a7-42c3-b721-842f3ed596a8"` 试试

**Comment by jixiaoyong** [comment]
可以连接了，谢谢。

**Comment by wgbbiao** [comment]
为什么设置成自己的，就不行呢？
