### ISSUE TITLE
请问可以自己控制请求到数据TTS的播报吗？？

### ISSUE THREAD

**Issue by leoncoding** [iFLYOS-OPEN/SDK-Android#2]
运行Demo后进行问答，OS返回的数据都是SDK内部自动播报，如果想自己定制TTS的声音，请问我们可以自己拿到返回数据进行播报吗？？

**Comment by jan4984** [comment]
返回的数据就是语音，你是想拿到播报的文本？

**Comment by leoncoding** [comment]
是的，我看到SDK文档里面是返回的二进制音频文件，我想自己拿到文本或者音频的URL控制语音的播报！不知道能否实现？？

**Comment by jan4984** [comment]
目前没有这个接口，所以客户端拿不到播报的文本。你可以

- 启用拦截器，拿到识别或者语义结果后自己处理决定返回什么给用户，包括播报内容
- 从官网和我们取得商务联系后，评估需求开发此接口

**Comment by leoncoding** [comment]
好的，非常感谢！
