### ISSUE TITLE
关于iFLYOS for Android开源项目代码的一些建议

### ISSUE THREAD

**Issue by Huliangyi** [iFLYOS-OPEN/SDK-Android#3]
大家好！
       客套话不多说了，直入主题，望优化，万分感激！
1、在com\iflytek\cyber\iot\show\core\impl\SpeechRecognizer\SpeechRecognizerHandler.java中：
      AudioReader中的mBuffer固定了640byte不能改，若改大或改小都不能用，而同样是科大讯飞公司的麦克风阵列降噪算法抛出来的声音却是1024大小的，如若此时IFLYOS里面的640不能改，那么在传输音频处理上就没有对接上，且不论我们能否自行拼接凑成640byte大小，由于音频是连续的，1024拆成640后多出来的也不能补0，且不知道后面到底还有没有1024继续传过来，这样就造成1024-640个字节被拆了后一直在等待，导致丢失....期望科大的专家们能做好不同产品的功能衔接。

2、代码较为耦合，例如：
      UI无法剥离困难，对于无屏设备来说，只需要初始化OS而不需要UI显示，UI这部分带来的性能消耗就可以省掉，但是实际操作时却比较困难，若直接干掉Luncher则会影响功能的初始化的一些动作，怕带来其他bug迟迟不敢下手

3、作为android应用Kotlin语言和Java语言混搭使用，由于Kotlin普及度问题，刚入手比较难读懂，增大了开发者的二次开发难度，何况还是与java混搭的。请问为何不全部用Java语言开发？建议开源项目要考虑代码简洁易懂性，另外没注释。

-------------------------------------
以上纯个人看法，感谢科大讯飞的专家们为科研做出的贡献，也同时希望能多为我们第三方开发者提供更好的支持，感谢！

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by jan4984** [comment]
我们会酌情改进，同时也欢迎贡献pr。

We will improve as appropriate, and we welcome the contribution of PR.

**Comment by seasonyuu** [comment]
1. 因为使用了 opus 编码来提升网络请求的性能，故客户端实现增加了一定的限制，后续开源版本会提供多种 SDK 版本选择，则可以自定 byte 数组长度。
2. 代码中主体部分为 EngineService，UI 部分的实现借助的是订阅，实际上可以完全剥离，并不耦合。
3. Kotlin 目前在 Andorid 开发者社区中处于主流，如果觉得项目中 Java 和 Kotlin 混合增加了理解难度，后续我们会考虑全部转换为 Kotlin 以降低代码理解难度。

代码注释方面我们会逐步跟进的，感谢反馈。
