### ISSUE TITLE
有java版本的吗

### ISSUE THREAD

**Issue by huangdali** [iFLYOS-OPEN/SDK-Android#4]
kotlin普及度不高，增加二次开发难度啊

**Comment by xingrz** [comment]
Java 和 Kotlin 可以互相调用的。最新的 Android Studio 已经支持 Kotlin。

**Comment by huangdali** [comment]
希望可以提供java版本的demo，kotlin看不懂啊，项目比较急，再去学kotlin怕是来不及了

**Comment by seasonyuu** [comment]
@huangdali https://stackoverflow.com/questions/34957430/how-to-convert-a-kotlin-source-file-to-a-java-source-file
