### ISSUE TITLE
有关此SDK的两个问题请尽快解答

### ISSUE THREAD

**Issue by 15538291327** [iFLYOS-OPEN/SDK-Android#6]
1.为什么IFLYO文档所介绍的API在此SDK中好多都没找到实现·，比如语音识别能力API的使用
2.为什么Start这么少，是否还处于不成熟状态，我们项目比较急如果此SDK不成熟不想浪费时间

**Comment by seasonyuu** [comment]
1. Android SDK 本质是基于 Linux SDK 的封装，所以文档中提到的大部分能力，实际上是 Linux SDK 实现的，然后在 Android SDK 中引入，你可以在代码中看到 [AAR](https://github.com/iFLYOS-OPEN/SDK-Android/blob/v2.x-oss/app/libs/ivs-android-sdk2.aar) 文件，其中包含了 Linux SDK 的相关实现。
2. 事实上已经是属于公开可接入状态，开源的 SDK Demo 提供了一个快速接入的方式。iFLYOS 目前已有数家公司接入商务合作，在目前的合作模式中，如果需要快速开发完善产品、或定制化的需求，我们希望你方可以通过商务途径联系到我司，进一步讨论开发需求。

**Comment by 15538291327** [comment]
我是不是可以理解为，目前IFLYOS官网给出的文档只是接口文档，有关于Android SDK的文档还是空白，接入的话以 SDK Demo的代码实现为准？

**Comment by seasonyuu** [comment]
https://doc.iflyos.cn/device/sdk/Android.html @15538291327 文档一直都在的，由于可以直接运行项目来参考，所以文档内容偏简洁，但对于有一定编程能力的人来说应该是足够的。如果你觉得有哪些不理解希望我们解释的地方，欢迎在 issue 提出，我们会及时解答并更新相关文档。
